import ReduxProvider from "@/components/ReduxProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { AuthContextProvider } from "@/contexts/AuthContext";

const roboto = Roboto({ weight: "400", subsets: ["greek"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <AuthContextProvider>
        <body className={roboto.className}>{children}</body>
        </AuthContextProvider>
      </ReduxProvider>
    </html>
  );
}
